spring:
  datasource:
    druid:
      url: jdbc:mysql://129.204.70.43:3306/crm?useUnicode=true&characterEncoding=UTF-8&userSSL=false&tinyIntlisBit=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
      username: crm_group23
      password: Group23@2019
